# Generated by Django 5.2.3 on 2025-07-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
