# Generated by Django 5.2.3 on 2025-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('class_name', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], max_length=2)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=9)),
                ('file', models.FileField(upload_to='syllabus/')),
            ],
        ),
    ]
