# Generated by Django 5.2.3 on 2025-07-22 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0003_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(upload_to='syllabus_files/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='year',
            field=models.CharField(choices=[('2022', '2022-23'), ('2023', '2023-24'), ('2024', '2024-25'), ('2025', '2025-26')], max_length=4),
        ),
    ]
