# Generated by Django 5.2.3 on 2025-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0004_syllabus_uploaded_at_alter_syllabus_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('theory_pdf', models.FileField(upload_to='unit_tests/theory/')),
                ('practical_pdf', models.FileField(upload_to='unit_tests/practical/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
