# Generated by Django 5.2.3 on 2025-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0005_unittest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('fy', 'FY'), ('sy', 'SY'), ('ty', 'TY')], max_length=10)),
                ('year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('theory_pdf', models.FileField(upload_to='unit_tests/theory/')),
                ('practical_pdf', models.FileField(upload_to='unit_tests/practical/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnitTest',
        ),
    ]
