# Generated by Django 5.2.3 on 2025-07-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0006_unittestupload_delete_unittest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
                ('link_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='news_files/')),
            ],
        ),
    ]
