# Generated by Django 5.2.3 on 2025-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0007_importantlink_newsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('fy', 'First Year (FY)'), ('sy', 'Second Year (SY)'), ('ty', 'Third Year (TY)')], max_length=10)),
                ('exam_session', models.CharField(choices=[('Oct/Nov 2023', 'Oct/Nov 2023'), ('March/April 2024', 'March/April 2024'), ('Oct/Nov 2024', 'Oct/Nov 2024'), ('March/April 2025', 'March/April 2025')], max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('upload_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='question_papers/')),
            ],
        ),
    ]
