# Generated by Django 5.2.3 on 2025-07-22 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0008_questionpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='exam_session',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='exam',
            field=models.CharField(default='Midterm', max_length=100),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='class_name',
            field=models.CharField(choices=[('fy', 'First Year'), ('sy', 'Second Year'), ('ty', 'Third Year')], max_length=2),
        ),
    ]
