# Generated by Django 5.2.3 on 2025-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0009_remove_questionpaper_exam_session_questionpaper_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='exam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
