# Generated by Django 5.2.3 on 2025-07-23 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0010_alter_questionpaper_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='exam',
            field=models.CharField(default='Midterm', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
