# Generated by Django 5.2.4 on 2025-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0011_alter_questionpaper_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestupload',
            name='practical_latex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unittestupload',
            name='theory_latex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
