# Generated by Django 5.2.4 on 2025-07-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0012_unittestupload_practical_latex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestupload',
            name='semester',
            field=models.CharField(default='First Semester', max_length=10),
        ),
        migrations.AddField(
            model_name='unittestupload',
            name='subject',
            field=models.CharField(default='Maths', max_length=100),
        ),
    ]
