# Generated by Django 5.2.4 on 2025-07-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0013_unittestupload_semester_unittestupload_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittestupload',
            name='practical_latex',
        ),
        migrations.RemoveField(
            model_name='unittestupload',
            name='theory_latex',
        ),
    ]
