# Generated by Django 5.2.4 on 2025-07-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0014_remove_unittestupload_practical_latex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2'), ('sem3', 'Semester 3'), ('sem4', 'Semester 4'), ('sem5', 'Semester 5'), ('sem6', 'Semester 6')], default='sem1', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
